sudo: required
language: node_js
cache:
  directories:
    - node_modules
    - apps/space/node_modules
    - apps/coin/node_modules
    - apps/member/node_modules
    - apps/coinsence-kit/node_modules
    - apps/shared/test-helpers/node_modules
notifications:
  email: false
node_js:
  - '11.0.0'
env:
  - TASK=lint
  - TASK=test:space
  - TASK=test:coin
  - TASK=test:member
#  - TASK=test:kit
  - TASK=coverage:space
  - TASK=coverage:coin
  - TASK=coverage:member
#  - TASK=coverage:kit
before_script:
  - testrpc > /dev/null &
  - sleep 5
script:
  - travis_wait 60 npm run $TASK
after_success:
  - ./node_modules/.bin/lcov-result-merger 'apps/*/coverage/lcov.info' | ./node_modules/.bin/coveralls
