sudo: required
language: node_js
cache:
  directories:
    - node_modules
    - apps/space/node_modules
notifications:
  email: false
node_js:
  - 'node'
env:
  - TASK=test:space
  - TASK=coverage:space
before_script:
  - npm prune
script:
  - travis_wait 60 npm run $TASK
after_success:
  - ./node_modules/.bin/lcov-result-merger 'apps/*/coverage/lcov.info' | ./node_modules/.bin/coveralls
