# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/coinsence-monorepo
    branches:
      only:
        - /.*/

    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3
      #- image: trufflesuite/ganache-cli
        # command: ganache-cli --deterministic -e 300 -p 8545 -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --accounts 30

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install Dependencies
          command: npm install
      - save_cache:
          name: Save NPM Package Cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint:fix
      - run: 
          name: Test Space app
          command: cd ./apps/space && npm run test
      - run: 
          name: Test Coin app
          command: cd ./apps/coin && npm run test
      - run: 
          name: Test Member app
          command: cd ./apps/member && npm run test
      - run: 
          name: Coverage Space app
          command: cd ./apps/space && npm run coverage
      - run: 
          name: Coverage Coin app
          command: cd ./apps/coin && npm run coverage
      - run: 
          name: Coverage Member app
          command: cd ./apps/member && npm run coverage
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts: 
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml